spring:
  application:
    name: geoszabaduloszoba-backend

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/cityscape_db
    username: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      encoding: UTF-8

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/cityscape-realm

  ai:
    google:
      genai:
        chat:
          options:
            model: gemini-1.5-flash

minio:
  url: http://localhost:9000
  bucketName: cityscape-avatars