spring:
  application:
    name: geoszabaduloszoba-backend

  profiles:
    active: local

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  datasource:
    url: jdbc:postgresql://localhost:5432/cityscape_db
    username: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      encoding: UTF-8

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/cityscape-realm

  ai:
    openai:
      base-url: https://api.groq.com/openai/
      chat:
        options:
          model: llama-3.1-8b-instant
          temperature: 0.2

minio:
  url: http://localhost:9000
  bucketName: cityscape-avatars