spring:
  application:
    name: geoszabaduloszoba-backend

  profiles:
    active: local

  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  datasource:
    url: jdbc:postgresql://pg-db:5432/cityscape_db
    username: postgres
    password: geolokacios_jelszo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      encoding: UTF-8

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cityscape-realm
          jwk-set-uri: http://keycloak:8080/realms/cityscape-realm/protocol/openid-connect/certs

  ai:
    openai:
      api-key: ${GROQ_API_KEY:dummy-key-for-groq}
      base-url: https://api.groq.com/openai/
      chat:
        options:
          model: llama-3.1-8b-instant
          temperature: 0.2

minio:
  url: http://minio:9000
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  bucketName: cityscape-avatars